Repository stackabletech/monitoring-operator, pull requests merged in 2021-07, with the labels that each got.

#1 Start prometheus
  .dockerignore
  .github/dependabot.yml
  .github/workflows/build_artifacts.yml
  .github/workflows/daily_security.yml
  .github/workflows/docker.yml
  .github/workflows/rust.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  README.adoc
  crd/Cargo.toml
  crd/src/bin/generate_crd.rs
  crd/src/error.rs
  crd/src/lib.rs
  deploy/config-spec/properties.yaml
  deploy/crd/monitoringcluster.crd.yaml
  docker/Dockerfile
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/building.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/installation.adoc
  examples/simple-monitoringcluster.yaml
  operator/Cargo.toml
  operator/src/error.rs
  operator/src/lib.rs
  scripts/prometheus-wrapper.sh
  server/Cargo.toml
  server/packaging/buildrpm.sh
  server/packaging/copy_assets.py
  server/packaging/debian/service
  server/packaging/rpm/SOURCES/stackable-monitoring-operator-server-VERSION/usr/lib/systemd/system/stackable-monitoring-operator-server.service
  server/packaging/rpm/SPECS/stackable-monitoring-operator-server.spec
  server/src/main.rs
Labels: type/enhancement

#5 Bugfix: path to binary in the CentOs service unit.
  server/packaging/rpm/SOURCES/stackable-monitoring-operator-server-VERSION/usr/lib/systemd/system/stackable-monitoring-operator-server.service
Labels: type/bug

#6 Added rule to avoid discover non metric container ports.
  operator/src/lib.rs
Labels: priority/medium, type/enhancement

#7 Adapted to operator-rs replica changes.
  Cargo.lock
  deploy/crd/monitoringcluster.crd.yaml
  examples/simple-monitoringcluster.yaml
  operator/src/lib.rs
Labels: priority/medium, type/enhancement
