Repository stackabletech/monitoring-operator, pull requests merged in 2021-08, with the labels that each got.

#15 Feature/collect node metrics
  Cargo.lock
  README.adoc
  crd/Cargo.toml
  crd/src/lib.rs
  deploy/config-spec/properties.yaml
  deploy/crd/monitoringcluster.crd.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/commandline_args.adoc
  docs/modules/ROOT/pages/configuration.adoc
  docs/modules/ROOT/pages/usage.adoc
  examples/simple-monitoringcluster.yaml
  operator/Cargo.toml
  operator/data/test/nodepods.yaml
  operator/data/test/nodepods_and_node.yaml
  operator/src/error.rs
  operator/src/lib.rs
  operator/src/prometheus.rs
Labels: priority/high, type/enhancement

#18 Feature/enable federation
  README.adoc
  crd/src/error.rs
  crd/src/lib.rs
  deploy/config-spec/properties.yaml
  deploy/crd/monitoringcluster.crd.yaml
  docs/modules/ROOT/pages/building.adoc
  docs/modules/ROOT/pages/configuration.adoc
  docs/modules/ROOT/pages/usage.adoc
  examples/simple-monitoringcluster.yaml
  operator/src/error.rs
  operator/src/lib.rs
  operator/src/prometheus.rs
Labels: priority/medium, type/enhancement

#29 Adapt to operator pod name and create config map
  .github/pull_request_template.md
  .github/workflows/rust.yml
  Cargo.lock
  LICENSE
  crd/Cargo.toml
  crd/src/bin/generate_crd.rs
  crd/src/lib.rs
  deny.toml
  operator/Cargo.toml
  operator/src/error.rs
  operator/src/lib.rs
  server/Cargo.toml
  server/build.rs
  server/src/main.rs
Labels: priority/high, type/enhancement

#34 Project updates
  .github/dependabot.yml
  .github/workflows/rust.yml
  CHANGELOG.md
  Cargo.lock
  crd/Cargo.toml
  deny.toml
  operator/Cargo.toml
  server/Cargo.toml
Labels: priority/low, type/enhancement
